# D34-1
* **假設我們資料中類別的數量並不均衡，在評估準確率時可能會有所偏頗**
* **試著切分出 y_test 中，0 類別與 1 類別的數量是一樣的 (亦即 y_test 的類別是均衡的)**
* **可以看見 y 類別中，有 160 個 類別 0，40 個 類別 1** 
* **請試著使用 train_test_split 函數，切分出 y_test 中能各有 10 筆類別 0 與 10 筆類別 1 **
* **(HINT: 參考函數中的 test_size，可針對不同類別各自作切分後再合併)**

In [3]:
import numpy as np
from sklearn.model_selection import train_test_split

X = np.arange(1000).reshape(200, 5)
y = np.zeros(200)
y[:40] = 1

In [25]:
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [78]:
X_train, X_test, y_train, y_test = train_test_split(X[:80], y[:80], test_size = 20, random_state = 42, stratify = y[:80])

In [79]:
X_test

array([[360, 361, 362, 363, 364],
       [ 15,  16,  17,  18,  19],
       [300, 301, 302, 303, 304],
       [ 65,  66,  67,  68,  69],
       [100, 101, 102, 103, 104],
       [270, 271, 272, 273, 274],
       [ 85,  86,  87,  88,  89],
       [310, 311, 312, 313, 314],
       [190, 191, 192, 193, 194],
       [120, 121, 122, 123, 124],
       [ 40,  41,  42,  43,  44],
       [125, 126, 127, 128, 129],
       [390, 391, 392, 393, 394],
       [340, 341, 342, 343, 344],
       [  5,   6,   7,   8,   9],
       [235, 236, 237, 238, 239],
       [195, 196, 197, 198, 199],
       [290, 291, 292, 293, 294],
       [315, 316, 317, 318, 319],
       [250, 251, 252, 253, 254]])

In [80]:
y_test

array([0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1., 0., 0., 1., 0., 1.,
       0., 0., 0.])